### ISSUE TITLE
threads management and single node of  toy configuration of Torque in the local machine?

### ISSUE THREAD

**Issue by zhenyisong** [SciLifeLab/NGI-RNAseq#120]
I have 18 human samples of which are paired-end RNA-seq data. I used the default setting --profile base to perform NGI-RNAseq procedure. However, the program quickly consumed a lot of hardware source. And I checked it using 'top' command and found that the load was above 70%.  Although I specified using the process.cpus = 40 to restrict the max CPU usage from my understanding. But it failed and the number of CUPS reached ~60 and my local machine is 64 (multi-core). 

I then used the Torque (4.2.7) and Maui (3.3) to simulate the 'PBS' environment.  I edited the base config file and specified executor to 'pbs' and cpus = 40. However, When I run the script, I used the qstat to check all submitted work, but most work is in sleep model (in queue, Q).  and I also used the top command to check the cpu and memory usage, they all were in the low load.

I think I missed something in configuration file either in Torque or nextflow config?

Here is the output from Torque (qmgr -c 'p s'):
[torque.txt](https://github.com/SciLifeLab/NGI-RNAseq/files/950522/torque.txt)

Here is the nextflow config adapted from the base and modified according to my understanding.
[wanglab.txt](https://github.com/SciLifeLab/NGI-RNAseq/files/950523/wanglab.txt)

Any suggestions? Thanks in advance.

**Comment by ewels** [comment]
Hi @zhenyisong,

I'll reply to specific parts of your message:

> _Although I specified using the `process.cpus = 40` to restrict the max CPU usage from my understanding. But it failed and the number of CUPS reached ~60 and my local machine is 64 (multi-core)._

`process.cpus` sets the number of CPUs to use _per process_, not in total. So Nextflow will have been trying to run all 18 samples in parallel with 40 CPUs each. If you're using the `local` executor then `executor.cpus` will set the _total_ max cpus to use (see the [nextflow docs](https://www.nextflow.io/docs/latest/config.html#scope-executor)) as you expected.

> _I then used the Torque (4.2.7) and Maui (3.3) to simulate the 'PBS' environment. I edited the base config file and specified executor to `pbs` and `cpus = 40`. However, When I run the script, I used the qstat to check all submitted work, but most work is in sleep model (in queue, Q)._

I guess that this is the same problem as above - you've told every process to ask Torque for 40 cpus, but you only have 64 available. As such, there is only space for one job to run at a time.

> _I also used the top command to check the cpu and memory usage, they all were in the low load._

Tools such as FastQC are not multithreaded and will only use one cpu, even if you allocate 40. If it was just FastQC running, then the cpu and memory usage will be low.

A couple of general points when looking at your config file:

Note that `process.cpus` sets the default value for all processes. This is overwritten by any process-specific configuration parameters. In your config you have the following:
```groovy
process.cpus     = 40
process {
    $star {
        cpus = 4
    }
}
```
Here the default is 40 cpus, but the STAR process is then only using 4. Also, you have a few typos - the FastQC and TrimGalore processes have `cpu = 8` instead of `cpus = 8`.

I hope this helps! Let us know how you get on..

Phil

**Comment by zhenyisong** [comment]
Quick question: if we do not use the 'Torque' to mimic the cluster in a single node machine, and use the 'local' model to forward the task, and if task 1 uses the executor.cpus = 40, and task 2 uses the excutor.cpus = 40 then, will this result in overlaod? I mean, our local machine has 64 cpus, the combine task (1&2) will consume all (64 cpus)?

Put another way, is there any thread managment procedure implemened or controled in the local, base script? Or do we have to add extra specification to perform the single task to avoid overload? Thanks again.

**Comment by ewels** [comment]
Hi @zhenyisong,

`executor.cpus` should only be stated once and applies to the entire pipeline. It shouldn't be set for each process, unlike `process.cpus`. The two should be used in combination - `process.cpus` says what each step requires. `excecutor.cpus` says that maximum that should be used at any time. If the pipeline wants to run processes with `process.cpus` that sum to more than `executor.cpus`, jobs will be held back by Nextflow until earlier ones have completed and there are more cpus available again. Does this make sense?

Exactly how you run the pipeline is kind of up to you. However, if you have a single machine and not many users, my suggestion would be to use the `base` profile in `local` mode. I would create my own custom config file that looks as follows:

```groovy
/* wanglab.config */
executor {
    name = 'local'
    cpus = 40
}
```

Then run the pipeline as follows:

```bash
nextflow run SciLifeLab/NGI-RNAseq -profile base -c /path/to/wanglab.config  # then other normal flags here...
```

The `base` profile config will determine the number of CPUs and amount of memory allocated for every step in the pipeline (default 2 cpus, used by tasks such as FastQC). The `executor` statement above will ensure that a maximum of 40 cpus will be requested at any time, meaning that there will always be at least 24 cpus left free for other users on the server.

Does this make sense and answer your question?

Phil

**Comment by zhenyisong** [comment]
I did not clarify my meaning. Supposed that two different users in our local single-node machine and they submit two jobs and both configuration files specify the executor number, which is equal to 30. And supposed that local machine is 64-cores. If running these two jobs at same time, the cpus consumed on the tasks are 30 at max or 60 (30 +30 ) at maximum?

**Comment by zhenyisong** [comment]
@ewels thanks.
