### ISSUE TITLE
trim_glore cannot find fastq files

### ISSUE THREAD

**Issue by MIAOKUI** [SciLifeLab/NGI-RNAseq#144]
Hi
I follow the instruction to install NGI-RNAseq pipeline and I try the following:

```
nextflow run NGI-RNAseq/main.nf --reads '/gpfs/software/nextflow/test_data/*_R{1,2}.fastq.gz' --genome hg19 --project test1
```

my fastq data was located on `/gpfs/software/nextflow/test_data/` , but trim_glore still cannot find fastq file:
```
ERROR ~ Error executing process > 'trim_galore (test)'

Caused by:
  Failed to submit job to grid scheduler for execution

Command executed:

  bsub

Command exit status:
  255

Command output:
  (more omitted..)
  
         bsub -pack job_submission_file
  
         bsub -h[elp] [all] [description] [category_name ...]
         [-option_name ...]
  
         bsub -V
  
  Categories and options
         Use the keyword all to display all options and the keyword
         description to display a detailed description of the bsub com-
         mand. For more details on specific categories and options, spec-
         ify bsub -h with the name of the categories and options.
  
  	  Category: dc
  	  Dynamic Cluster only. Submit Dynamic Cluster jobs:
  	  -dc_chkpntvm, -dc_mtype, -dc_tmpl, -dc_vmaction.
  
  	  Category: io
  	  Specify input/output files and directories: -cwd, -e, -eo, -f,
  	  -i, -is, -o, -oo, -outdir, -tty.
  
  	  Category: limit
  	  Specify limits: -c, -C, -D, -F, -hl, -M, -p, -S, -T, -ul, -v,
  	  -W, -We.
  
  	  Category: notify
  	  Control user notification: -B, -K, -N, -u.
  
  	  Category: pack
  	  Submit job packs (single files containing multiple job
  	  requests): -pack.
  
  	  Category: properties
  	  Specify job submission properties: -app, -ar, -E, -env, -Ep,
  	  -g, -I, -Ip, -Is, -IS, -ISp, -ISs, -IX, -J, -Jd, -jsdl,
  	  -jsdl_strict, -k, -K, -L, -P, -q, -Q, -r, -rn, -rnc, -s, -sla,
  	  -sp, -wa, -wt, -XF, -Zs.
  
  	  Category: resource
  	  Specify resources and resource requirements: -clusters, -freq,
  	  -hostfile, -m, -n, -network, -R, -U.
  
  	  Category: schedule
  	  Control job scheduling and dispatch: -a, -b, -clusters, -ext,
  	  -G, -H, -Lp, -mig, -t, -ti, -U, -w, -x.
  
  	  Category: script
  	  Use job scripts: -Zs.
  

Work dir:
  /gpfs/software/nextflow/work/c3/334795be28241ac16775755acf3009

```

when run the `.comand.sh` inside, it appears that trim_glore cannot find fastq file.

**Comment by ewels** [comment]
Hi @MIAOKUI,

Sorry for the delay in replying, I've just got back from a holiday. From the error log you posted, this appears to be an error to do with your cluster job scheduler rather than anything specific to Trim Galore or finding files. Specifically, it's the `bsub` command that's failing with the error message `Failed to submit job to grid scheduler for execution`.

The second thing you mention about running `.command.sh` manually and not finding fastq files may be a separate second problem.

I guess that you must have edited / created a configuration file. Could you please paste the contents of this? It may also be worth asking for help on the main [nextflow gitter channel](https://gitter.im/nextflow-io/nextflow) as problems with job submission are core nextflow behaviour and not tied directly to this pipeline (though I'm happy to try and help if I can).

For the second problem of not finding fastq files - please could you paste the following:

1. The contents of the work directory (using `ls -la` to show hidden files too)
2. The contents of the `.command.sh` file
3. The stdout messages that you get when you try to execute this file manually (`bash command.sh`)

Thanks,

Phil

**Comment by Hammarn** [comment]
Closing this since @MIAOKUI hasn't responded. Feel free to reopen.
