### ISSUE TITLE
GFF file input

### ISSUE THREAD

**Issue by JohnHellgren** [SciLifeLab/NGI-RNAseq#184]
Hello,
Is it possible to use a GFF file for the annotations instead of a GTF file?
Or do you know of any good means of converting between these two formats?

Kind regards,
John Hellgren

**Comment by ewels** [comment]
Hi @JohnHellgren,

GFF can be pretty variable, so it's difficult to give a generic answer. Depending on how your GFF file looks, it's possible that it may just work in the pipeline already (GTF is a subset of GFF). Where did you get your GFF file? What happens if you try running the pipeline with it?

Cufflinks & StringTie have some tools for working with GFF files I think (though I haven't tried using them myself). See http://ccb.jhu.edu/software/stringtie/gff.shtml and elsewhere.

Phil

**Comment by JohnHellgren** [comment]
I would like to use this genome assembly:
https://github.com/AbeelLab/nanopore-cenpk113-7d
But they only provide an GFF file (maybe I can ask if they can provide an GTF file as well).

It looks like STAR can handle GFF files, but I wasn't sure how to tell the pipeline to use it.
The STAR manual says to use this command:

```
--sjdbGTFtagExonParentTranscript Parent
```

but the error I got was that the pipeline was missing a GTF file.

**Comment by ewels** [comment]
Ok - just use `--gtf filename.gff` to run the pipeline with your file (see [docs](https://github.com/SciLifeLab/NGI-RNAseq/blob/master/docs/usage.md#--star_index---hisat2_index---fasta---gtf---bed12)).

Using custom STAR parameters like that isn't possible without editing the pipeline directly. I don't think that we will be adding in support for GFF files like this any time soon sorry, so if the pipeline doesn't work then your best bet is trying to convert GFF to GTF first I think.

Looking into that repo and the paper behind it, it sounds like they have generated their annotation using [MAKER2](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-491) which outputs GFF3 files specifically. I think you should be able to convert this to GTF using tools such as [gffread](https://github.com/gpertea/gffread) and others.

Phil

**Comment by ewels** [comment]
Closing this issue now - feel free to comment if there's anything else to follow up on..
