### ISSUE TITLE
genome configuration file

### ISSUE THREAD

**Issue by PycnopodiaD** [SciLifeLab/NGI-RNAseq#236]
Hi,

This is probably not the best question, but I really cannot find the documentation concerning the  ' configuration setup to save sets of reference files for your own use, even if they are not part of the iGenomes resource', which is supposed to be found somewhere here;
https://www.nextflow.io/docs/latest/config.html#configuration-file

I have my own genome and annotation files. 
It would also be good to know how to name the file and any other information to make it easier for me or anybody else.

Also just another question, would it be possible to use a .gff file instead of a .gtf file? I have made the .gtf file from my .gff file, but I guess it won't be perfect.

Thanks.

**Comment by PycnopodiaD** [comment]
Hi,
I was just wondering if anybody could help me. I realized that I posted  this just before summer, so I will just try again in case anybody can help. Otherwise I will just continue by doing everything one step at a time.

I would like to say that if you don't know how to help me that maybe you should rename the pipeline, so that people who are not working on human know that they shouldn't bother.

**Comment by ewels** [comment]
Hi @PycnopodiaD,

You can find documentation about using your own reference genomes with the NGI-RNAseq pipeline here: https://github.com/SciLifeLab/NGI-RNAseq/blob/master/docs/usage.md#reference-genomes

You can add these paths to a nextflow config file for convenience if you like, or you can pass them on the command line when you run the pipeline. Hopefully the above docs are clear, but please let us know if you need any pointers! It shouldn't matter how you name the files as long as the paths supplied are valid.

> Also just another question, would it be possible to use a .gff file instead of a .gtf file?

Great question, and something that others have also requested. With this version of the pipeline at SciLifeLab/NGI-RNAseq the answer is no - not possible sorry. However, we've recently moved the pipeline to a new location (this repository will be archived very soon). We added support for both GTF or GFF files in the next release here - you simply use `--gff` instead of `--gtf` and the pipeline will convert on the fly for you. The pipeline will have it's first release hopefully today and be ready to use. You can find it at https://github.com/nf-core/rnaseq

Read more about the nf-core initiative at http://nf-co.re/ and you can chat to us to get help at https://gitter.im/nf-core/Lobby

Phil

**Comment by ewels** [comment]
To follow - we've just pushed the version 1.0 release: https://github.com/nf-core/rnaseq/releases/tag/1.0
